### PR TITLE
this will fix for hscript error

### PR DESCRIPTION
**Pull request by Hiho2950**
SScript what is used now not the official HScript

### CODE REVIEW

**Comment by Hiho2950** [comment]
there is another things on modchartFile that i had fix it before but it will takes long and the same cause on it sscript is used not hscript

**Comment by EdwhakKB** [comment]
Sscript got removed if im right

**Comment by Hiho2950** [comment]
> Sscript got removed if im right

i think but it still on haxelib and try to use brewscript instead

**Comment by EdwhakKB** [comment]
Hscript got fixed so thank you!

**Pull request closed without merging**
