### PR TITLE
some fixes

### PR DESCRIPTION
**Pull request by 2JENO**

### CODE REVIEW

**Comment by glowsoony** [comment]
Sorry all of this things are already on this modcharting-tools repo but thanks for the help anyways!

**Comment by 2JENO** [comment]
image
yay my commit

**Comment by 2JENO** [comment]
> Sorry all of this things are already on this modcharting-tools repo but thanks for the help anyways!

cuz i did it from Edwhak discord

**Comment by 2JENO** [comment]
> > Sorry all of this things are already on this modcharting-tools repo but thanks for the help anyways!
> 
> cuz i did it from Edwhak discord

so that is by me lol

**Comment by glowsoony** [comment]
Yeah I see that, thanks for the FlxSound fix though.

**Comment by 2JENO** [comment]
image
image

**Comment by 2JENO** [comment]
> Yeah I see that, thanks for the FlxSound fix though.

np!

**Pull request closed without merging**
