### PR TITLE
GPU Stuff

### PR DESCRIPTION
**Pull request by 2JENO**
GPU Guide, editor fixes!

### CODE REVIEW

**Comment by 2JENO** [comment]
this is for people who don't know GPU Cache like me(invisible sustain notes).

**Comment by glowsoony** [comment]
Thanks for the help!

**Comment by 2JENO** [comment]
> Thanks for the help!

can you update readme too?

**Comment by glowsoony** [comment]
named the thing wrong but I updated it.

**Comment by 2JENO** [comment]
oh i fixed some readme for credit check my fork

**Pull request closed without merging**
