### PR TITLE
WHY DONT WRITE OVERRIDE

### PR DESCRIPTION
**Pull request by 2JENO**

### CODE REVIEW

**Comment by 2JENO** [comment]
update this

**Comment by glowsoony** [comment]
One thing, FlxTweenManager DOES NOT by default have there Tweens so doing "override" is pretty useless.

**Comment by 2JENO** [comment]
well,

**Comment by 2JENO** [comment]
source/managers/TweenManager.hx:12: characters 18-33 : Field bezierPathTween should be declared with 'override' since it is inherited from superclass flixel.tweens.FlxTweenManager
source/managers/TweenManager.hx:19: characters 18-36 : Field bezierPathNumTween should be declared with 'override' since it is inherited from superclass flixel.tweens.FlxTweenManager

**Comment by 2JENO** [comment]
> One thing, FlxTweenManager DOES NOT by default have there Tweens so doing "override" is pretty useless.

not useless

**Comment by glowsoony** [comment]
That really doesn't make sense since FlxTweenManager was removed from this Lib awhile ago so it's not a parent class holding those tweens meaning no override is needed unless FlxTweenManager has the traits WHICH IT DOESN'T AND SHOULDN'T contain the parent traits.

**Pull request closed without merging**
